### ISSUE TITLE
400 Bad Request on Nerby Stations endpoint

### ISSUE THREAD

**Issue by heppth** [meteostat/meteostat-server#5]
I am new to meteostat API, signed up on RapidAPI and tried to use the API.

The Nerby Stations endpoint seems to have a problem, because it is always returning 400 Bad Request. Even with default parameters via [Test Endpoint](https://rapidapi.com/meteostat/api/meteostat/).

My API key seems to be fine, because the Daily Station Data endpoint is working as expected.

Tested URL: `https://meteostat.p.rapidapi.com/stations/nearby?lat=51.5085&lon=-0.1257`

**Comment by clampr** [comment]
Hi @heppth,

I looked into this issue and I think I fixed it. Feel free to re-open this issue if the error persists.
